### ISSUE TITLE
Variant semantics?

### ISSUE THREAD

**Issue by ice1000** [owo-lang/voile-rs#11]
https://github.com/owo-lang/voile-rs/blob/5633dc8c7d793711487a89b6bc239afb2fcc38dc/src/syntax/abs/ast.rs#L18

Currently there's only a label -- without a type expression that represents its argument type.

If I write an expression `'Label ParamType`, it'll be parsed as `App(ConsType(Label), Expr(Ident))`,
which indicates that the type of `'Label` is `Lam(Type /* param type */, Sum(Ref(0 /* DBI */)))`, right?

Does that look good to you guys?

Assigned people are supposed to participate the discussion.

**Comment by oraluben** [comment]
So `Cons`s could be treated as trivial functions? Meanwhile they are also "member" of `Sum`? LGTM.

**Comment by oraluben** [comment]
I may have some confusion on the problem, but yes, in `App` `'Label` should have that type, I don't see any problem here.

**Comment by anqurvanillapy** [comment]
It's easy to do `Lam`s' equality check, using eta-expansions.  I'm sorry that I'm currently not that able to join this discussion due to the lack of knowledge and project context.

**Comment by ice1000** [comment]
@oraluben yeah I guess the semantics become quite similar to Haskell

**Comment by ice1000** [comment]
Tycking `Variant` is basically done in recent commits, closing.
