### ISSUE TITLE
Why isn't `VecDbiEnv` a `Vec`?

### ISSUE THREAD

**Issue by ice1000** [owo-lang/voile-rs#14]
We can replace `VecDbiEnv` with a `Vec`.

These codes are affected:

https://github.com/owo-lang/voile-rs/blob/12194c780c0241455b0f803334284067fd227b5b/src/cli/mod.rs#L24-L36
https://github.com/owo-lang/voile-rs/blob/88b2aa3701b7472eb680305f03187dc361afe6cc/src/syntax/abs/tests.rs#L32
https://github.com/owo-lang/voile-rs/blob/88b2aa3701b7472eb680305f03187dc361afe6cc/src/syntax/abs/tests.rs#L38

after all these we can start testing our trans/check functions

**Comment by ice1000** [comment]
@oraluben promised me to "do this refactoring tomorrow" the day before yesterday.

**Comment by ice1000** [comment]
We should consider publishing a new version on docs.rs since we have enhanced our docs a lot.

**Comment by oraluben** [comment]
_(:з」∠)_ sorry my late
