### ISSUE TITLE
Value context should be split into global and local?

### ISSUE THREAD

**Issue by ice1000** [owo-lang/voile-rs#15]
https://github.com/owo-lang/voile-rs/blob/c9f887054313e420b3f8725b36743f06a5a9f7d5/src/check/monad/state.rs#L22-L23

Because we're already splitting the local and global **typing** context, should we split the **value** context as well?

**Comment by oraluben** [comment]
Local gamma is used when checking dependent types, what is a "local env" for?

**Comment by oraluben** [comment]
https://github.com/owo-lang/voile-rs/blob/c9f887054313e420b3f8725b36743f06a5a9f7d5/src/check/monad/state.rs#L24-L26

by the way, I think it's not necessary anymore, for the size could be got by `DbiEnv.len()`

**Comment by ice1000** [comment]
> Local gamma is used when checking dependent types, what is a "local env" for?

Which stores the parameters of lambda abstractions. That will be stored inside of the compiled closure.

**Comment by ice1000** [comment]
> by the way, I think it's not necessary anymore, for the size could be got by DbiEnv.len()

It can still be the local env size. What do you think?

**Comment by ice1000** [comment]
> https://github.com/owo-lang/voile-rs/blob/c9f887054313e420b3f8725b36743f06a5a9f7d5/src/check/monad/state.rs#L24-L26
> 
> by the way, I think it's not necessary anymore, for the size could be got by `DbiEnv.len()`

`DbiEnv.len()` is expensive

**Comment by ice1000** [comment]
But we can replace `DbiEnv` with `Vec`

**Comment by ice1000** [comment]
> > Local gamma is used when checking dependent types, what is a "local env" for?
> 
> Which stores the parameters of lambda abstractions. That will be stored inside of the compiled closure.

Now we don't store.

**Comment by ice1000** [comment]
Closing in favor of

https://github.com/owo-lang/voile-rs/blob/178c67f32bdc2a61584326b68e766de05c6a91f7/src/check/monad/state.rs#L7-L35
