### ISSUE TITLE
`SyntaxInfo` design

### ISSUE THREAD

**Issue by oraluben** [owo-lang/voile-rs#171]
For inserted meta (which is not in original source code), we need another type of `SyntaxInfo`.
Here's my first design:
```rust
pub enum SyntaxInfo {
    SourceInfo(SourceInfo),
    ImplicitMetaInfo(Box<Self>),
}
```

But we are not sure if `ImplicitMetaInfo(Box<Self>)` is necessary. For simplicity, `ImplicitMetaInfo(SourceInfo)` is better, and there looks not be any differences.

**Comment by oraluben** [comment]
I admit for current `SyntaxInfo` (with two variants), `ImplicitMetaInfo(SourceInfo)` is enough for no matter error report or something else.
But, consider
```
pub enum SyntaxInfo {
    SourceInfo(SourceInfo),
    ImplicitMetaInfo(SourceInfo),
    SomeOtherAutoInsertedTerm(SourceInfo),
}
```
if nested `ImplicitMetaInfo` is possible, we may also have something like `ImplicitMetaInfo(SomeOtherAutoInsertedTerm)`. In that case `ImplicitMetaInfo(SomeOtherAutoInsertedTerm)` and `ImplicitMetaInfo(SourceInfo)` are different.

But but, I'm not able to figure out in what situation we could get a nested `ImplicitMetaInfo`.

**Comment by ice1000** [comment]
> For inserted meta (which is not in original source code), we need another type of SyntaxInfo.
Here's my first design:

If I were you I'll use the `SyntaxInfo` from the function term, like when I inserted a meta here `f <meta> a` because `f`'s inferred type is `{} -> () -> blabla`, I'll copy `f`'s `SyntaxInfo` to the added meta.
This also happens elsewhere like type inference, I'll show you.

**Comment by ice1000** [comment]
https://github.com/owo-lang/voile-rs/blob/e284e6da7e486dedd7acbb3c9c0e1bc665880bc2/src/check/expr.rs#L454-L457

**Comment by oraluben** [comment]
I see. If we are using "parent" info for "child" but not exactly create a type of info in each case, it looks better to do that in implicit, for consistency.

**Comment by ice1000** [comment]
We can add a `is_generated : bool` field to indicate that whether this `syntax_info` is generated
