### ISSUE TITLE
Is this translation correct?

### ISSUE THREAD

**Issue by ice1000** [owo-lang/voile-rs#44]
https://github.com/owo-lang/voile-rs/blob/5092a41fe1d6c3af24a51a806817a4e5c694c52a/src/syntax/abs/trans.rs#L40

**Comment by oraluben** [comment]
I'm quite not sure. Currently `AbsDecl::None` will only occur as a parameter in lambda, which has no "sign" or "impl". This rule is not supposed to be reached now.

**Comment by ice1000** [comment]
IIUC it's because this part is not yet implemented so you're not sure?

https://github.com/owo-lang/voile-rs/blob/a75a6ca1559024442a12f03b793d08ca6bec60df/src/syntax/abs/trans.rs#L104-L112

**Comment by ice1000** [comment]
Let's test lambda translation

**Comment by ice1000** [comment]
Removed in #68
