### ISSUE TITLE
Lambda syntax design & parser

### ISSUE THREAD

**Issue by ice1000** [owo-lang/voile-rs#46]
Let's vote.

Option 0 (Haskell, add a 🎉 to vote for this):

```haskell
\x -> x
\x y -> y x
```

Option 1 (Idris, add a 🚀 to vote for this):

```idris
\x => y
\x => \y => y x
```

Option 2 (Mini-TT, add a ❤️ to vote for this):

```sml
\x. x
\x y. y x
```

**Comment by ice1000** [comment]
D S S Q

**Comment by ice1000** [comment]
I'm sorry -- I have already implemented the parser. I've just forgotten it. My bad.

However, I did change the syntax according to this vote. We'll see.

**Comment by ice1000** [comment]
... and please continue vote, new comers.

**Comment by anqurvanillapy** [comment]
Is this vote in progress?  Why was this issue closed?  Anyway the option 1 with the bonus <kbd>Shift</kbd> for `->` hurts me.

**Comment by ice1000** [comment]
This issue is closed by a commit, which means it's fixed as an issue or implemented as a new feature
